# Generated by Django 3.2.7 on 2021-09-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='name',
            field=models.CharField(default='random', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jar',
            name='date_created',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('penalty', models.IntegerField()),
                ('jar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jar.jar')),
            ],
        ),
    ]
