# Generated by Django 3.2.7 on 2021-09-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0002_auto_20210926_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(default='https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png'),
            preserve_default=False,
        ),
    ]
