# Generated by Django 3.2.7 on 2021-09-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jar', '0003_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='submitter',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
